In [3]:
import numpy as np

In [38]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [6]:
type(a)

numpy.ndarray

In [12]:
a

array([10,  2,  3,  4,  5])

In [23]:
a.shape

(5,)

In [24]:
print(a)

[4 2 3 4 5]


In [14]:
a[0]=4.2
a

array([4, 2, 3, 4, 5])

In [16]:
lista = [1, 2, 'LC', 4.0]
array = np.array([1, 2, 'LC', 4.0])

print("Essa é a lista: ", lista)
print("Esse é o array: ", array)

Essa é a lista:  [1, 2, 'LC', 4.0]
Esse é o array:  ['1' '2' 'LC' '4.0']


In [18]:
array = np.array([1, 2, 4.0])
array

array([1., 2., 4.])

In [21]:
"""
Código comparando performance
"""

import time
import numpy as np

size_of_vec = 10000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.007579326629638672 0.004695892333984375
Numpy is in this example 1.6140333062550771 faster!


In [22]:
"""
Diferenças
"""
lista = [1, 2, 3, 4]
array = np.array([1, 2, 3, 4])

print("Essa é a lista: ", lista)
print("Esse é o array: ", array)

Essa é a lista:  [1, 2, 3, 4]
Esse é o array:  [1 2 3 4]


In [32]:
b = np.array([
                [9.0, 8.0, 7.0],
                [6.0, 5.0, 4.0]
                                ])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


____________
____________
**Exercício:** Crie em numpy a seguinte matriz:
$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

In [33]:
# Resposta
array = np.array([[1, 2, 1], [3, 0, 1], [0, 2, 4]])
array

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4]])

In [34]:
print(array)

[[1 2 1]
 [3 0 1]
 [0 2 4]]


_______________
_______________

### 3D arrays

Nesse caso, teremos um tensor tridimensional que visualmente pode ser interpretado das seguintes formas:


<img src="tensor_3-2-5.png"  style="width: 500px" />

In [35]:
c = np.array([[[0,   1,  2,  3,  4], [ 5,  6,  7,  8,  9]], 
              [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
              [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]])
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [36]:
print(c)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [39]:
a

array([1, 2, 3, 4, 5])

In [40]:
print(a.ndim)
print(a.shape)
print(a.size)

1
(5,)
5


In [41]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [42]:
print(b.ndim)
print(b.shape)
print(b.size)

2
(2, 3)
6


In [43]:
len(b)

2

In [44]:
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [45]:
print(c.ndim)
print(c.shape)
print(c.size)

3
(3, 2, 5)
30


In [46]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], 
              [8, 9, 10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19, 20, 21]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [47]:
a[2,4]

19

In [49]:
a[2][4]

19

In [50]:
a[2,-2]

20

In [52]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [51]:
a[:,2]

array([ 3, 10, 17])

In [53]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [56]:
a[1,0:6:3]

array([ 8, 11])

In [59]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
# negativo na coluna
a[0, 1:-1:2]

array([2, 4, 6])

In [60]:
# negativo no step
a[0, -1:1:-2]

array([7, 5, 3])

In [61]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [62]:
a[0,2]=99

In [63]:
a

array([[ 1,  2, 99,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [66]:
a[:,4]=50

In [67]:
a

array([[ 1,  2, 99,  4, 50,  6,  7],
       [ 8,  9, 10, 11, 50, 13, 14],
       [15, 16, 17, 18, 50, 20, 21]])

In [70]:
my_slice[0]

2

In [71]:
my_slice[0] = -1
my_slice

array([-1,  3])

In [72]:
my_array

array([ 1, -1,  3,  4])

In [74]:
x = [1, 2, 3]
y = x[0:2]
print(y)
y[0] = "a change"
y

[1, 2]


['a change', 2]

In [75]:
x

[1, 2, 3]

In [76]:
my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]]
my_slice[0] = -1
my_array

array([1, 2, 3])

In [78]:
my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]].copy()
my_slice[0] = -1
my_array

array([1, 2, 3])

In [79]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [80]:
a+2

array([3, 4, 5, 6])

In [81]:
a-2

array([-1,  0,  1,  2])

In [88]:
a*2

array([2, 4, 6, 8])

In [87]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [85]:
a2 = a**2
a2.dtype

dtype('int64')

In [89]:
a**2

array([ 1,  4,  9, 16])

_______________________
_______________________

In [90]:
a+=7

In [91]:
a

array([ 8,  9, 10, 11])

In [92]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

# Exemplo de soma
a+b

array([2, 2, 4, 4])

In [93]:
# Exemplo de multiplicação
a*b

array([1, 0, 3, 0])

In [96]:
# Exemplo de potenciação
c = a**b
c

array([1, 1, 3, 1])

In [97]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.min(stats)

1

In [101]:
stats.max()

6

________________
________________
**Exercício:** encontre a média e o desvio padrão da matriz, sabendo que os métodos são representados por `np.mean()` e `np.std()`, respectivamente.

In [102]:
# média dos valores de stats
np.mean(stats)

3.5

In [103]:
stats.mean()

3.5

In [104]:
# desvio padrão dos valores de stats
stats.std()

1.707825127659933

_____________
_____________

In [105]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.min(stats[:,2], axis=0)

3

In [112]:
np.min(stats, axis=0)[2]

3

In [107]:
np.min(stats, axis=1) 

array([1, 4])

In [113]:
stats.min(axis=1)

array([1, 4])

_________________
_________________
**Exercício:** Realize a soma para cada linha e para cada coluna:

In [117]:
# linha
stats.sum(1)

array([ 6, 15])

In [116]:
# coluna
stats.sum(axis=0)

array([5, 7, 9])

___________
___________


In [122]:
mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

array([[ 1, 10],
       [20, 30]])

In [123]:
mat.shape

(2, 2)

In [125]:
mat[mat > 10]

array([20, 30])

In [126]:
mat_2 = mat>10 
mat*mat_2

array([[ 0,  0],
       [20, 30]])

In [127]:
mat

array([[ 1, 10],
       [20, 30]])

In [128]:
mat_2

array([[False, False],
       [ True,  True]])

In [132]:
a =np.array([1, 2, 0, False])
a

array([1, 2, 0, 0])

In [134]:
mat

array([[ 1, 10],
       [20, 30]])

In [133]:
filt = (mat > 10) & (mat <= 25)
mat[filt]

array([20])

In [140]:
mat[(mat > 10) & (mat <= 25)]

array([20])

In [142]:
mat

array([[ 1, 10],
       [20, 30]])

In [141]:
filt = (mat == 1) | (mat > 20)
mat[filt]

array([ 1, 30])

In [143]:
filt = (mat > 10) & (mat <= 25)
mat[~filt]

array([ 1, 10, 30])

In [149]:
filt

array([[False, False],
       [ True, False]])

In [144]:
mat[~((mat > 10) & (mat <= 25))]

array([ 1, 10, 30])

In [145]:
2 & 4

0

In [148]:
10 | 100

110

In [150]:
u = np.array([-1,  2, -3])
print("u =", u)
print()

u = [-1  2 -3]



In [153]:
u[u<0] = 0

In [154]:
u

array([0, 2, 0])

In [155]:
np.where(u<0, 0, u)

array([0, 2, 0])

In [161]:
np.null

AttributeError: module 'numpy' has no attribute 'null'

In [156]:
a = np.array([[1, 2, 3, np.nan, 5], [np.nan, 7, 8, 9,10]])
a

array([[ 1.,  2.,  3., nan,  5.],
       [nan,  7.,  8.,  9., 10.]])

In [159]:
np.isnan(a)

array([[False, False, False,  True, False],
       [ True, False, False, False, False]])

In [160]:
np.isnan(a).sum()

2

## Material de Aprofundamento

### Seleção passando listas

Podemos selecionar elementos específicos de um array passando uma lista de posições:


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a[[1, 2, 5, 8]]

### Comparando arrays

In [ ]:
u = np.arange(4).reshape(2,2)
v = 2*np.ones((2,2))

In [ ]:
u

In [ ]:
v

In [ ]:
w = u > v
print(w)

In [ ]:
u[u > v]

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
before

In [ ]:
after = before.reshape((4, 2)) # tem que possuir a mesma quantidade no size!
after

In [ ]:
before.reshape((-1, 2)) # o -1 representa quantas linhas for preciso para ter 2 colunas

In [ ]:
before.reshape(2, 2, 2)

In [ ]:
mat

In [ ]:
np.any(mat > 10, axis=0)

In [ ]:
np.any(mat > 10, axis=1)

In [ ]:
np.any(mat > 10)

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

In [ ]:
h1 = np.ones((2, 4))
print(h1)
print()

h2 = np.zeros((2, 2))
print(h2)

In [ ]:
np.hstack((h1, h2))

In [ ]:
np.random.rand(4, 2)

In [ ]:
v = np.random.normal(10, 1, (4,4))
print(v)


In [ ]:
np.random.randint(low=0, high=100, size=100)


In [ ]:
np.random.randint(7, size=(3, 3))

In [ ]:
np.random.seed(1000)
v = np.random.rand(4)
print(v)

np.random.seed(1000)
v = np.random.rand(4)
print(v)


In [ ]:
np.zeros(5)

In [ ]:
np.zeros((2,3))

In [ ]:
np.zeros((2, 2, 3))

In [ ]:
np.ones((4, 2, 2), dtype='int32')

In [ ]:
np.ones((2, 2)) * 10

In [ ]:
np.full((2, 2), 99)

In [ ]:
np.full_like(c, 4)

## Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array[array%2==1]

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [ ]:
# primeira forma de solução
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
[0 if i%2==1 else i for i in arr ]

# segunda forma de solução
arr[arr%2==1] = 0
arr

# terceira forma de solução
np.where(arr % 2 == 1, 0, arr)

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [ ]:
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:10]

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [ ]:
# Input
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [ ]:
condition = (iris[:, 2] > 1.5) & (iris[:, 0] < 5.0)
iris[condition]

6 - Esse dataset possui nans?

In [ ]:
iris[np.isnan(iris)]

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [ ]:
# Solução
# Computa o volume
sepallength = iris[:, 0].astype('float')
petallength = iris[:, 2].astype('float')
volume = np.pi * petallength * (sepallength**2)/3

# Adiciona a segunda dimensão no vetor de volume
# volume = volume[:, np.newaxis]
volume = volume.reshape(-1,1)

# Adiciona o vetor volume como coluna da matriz original
out = np.hstack([iris, volume])

# View
out[:4]